- name: modify zabbix-agent-config(replace_IPaddress)
  hosts: all
  sudo: yes
  roles:
    - name: common
      tags:
        - common
    - name: zabbix-agent_conf_replace_IPaddress
      tags:
        - zabbix-agent_conf_replace_IPaddress